// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8WMaNZgFxuvFaq0hKGk8us50_Lq7IcZs',
    appId: '1:613566622125:web:b78973f6d39a09b0da1924',
    messagingSenderId: '613566622125',
    projectId: 'surveytes-6bc88',
    authDomain: 'surveytes-6bc88.firebaseapp.com',
    storageBucket: 'surveytes-6bc88.firebasestorage.app',
    measurementId: 'G-KLRTXH67SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2y49pt6LP6sHWi8HWQ2SWJT5AQfPggs',
    appId: '1:613566622125:android:baa903d873d9f565da1924',
    messagingSenderId: '613566622125',
    projectId: 'surveytes-6bc88',
    storageBucket: 'surveytes-6bc88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6SRZwWkWCAqhh4mW5aqowF7j1fZBOmJk',
    appId: '1:613566622125:ios:b8c52b31ea273511da1924',
    messagingSenderId: '613566622125',
    projectId: 'surveytes-6bc88',
    storageBucket: 'surveytes-6bc88.firebasestorage.app',
    iosClientId: '613566622125-p1cltt6nq37rhrt8oqrnci5ct8rnufts.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
